// The doctors catalogue written by seed.js. Every person and hospital here is fictional: names
// are invented for the demo and don't refer to real doctors or real hospitals.
//
// Fields match DoctorMapper in the app. Times are Asia/Kathmandu, "HH:mm" 24-hour. Weekday keys
// are sun..sat; a day that is missing is closed. Specialty keys match the app's Specialty enum.

const morning = { start: '09:00', end: '13:00' };
const afternoon = { start: '14:00', end: '17:00' };
const evening = { start: '16:00', end: '19:00' };

/** Sunday to Friday, Saturday off (the usual Nepali working week). */
const weekdays = (...ranges) => ({ sun: ranges, mon: ranges, tue: ranges, wed: ranges, thu: ranges, fri: ranges });

export const doctors = [
  {
    id: 'doc-001',
    name: 'Anjali Basnet',
    specialty: 'general_physician',
    hospital: 'Sunrise Valley Hospital',
    feeNpr: 500,
    experienceYears: 8,
    slotMinutes: 15,
    bio: 'Family medicine for adults and older people: fevers, infections, diabetes and blood pressure checks.',
    weeklySchedule: weekdays(morning, afternoon),
  },
  {
    id: 'doc-002',
    name: 'Rajan Khadka',
    specialty: 'cardiology',
    hospital: 'Himal View Hospital',
    feeNpr: 1500,
    experienceYears: 18,
    slotMinutes: 20,
    bio: 'Heart health, chest pain, high blood pressure and follow-up after heart procedures.',
    weeklySchedule: { sun: [morning], tue: [morning], thu: [morning, afternoon] },
  },
  {
    id: 'doc-003',
    name: 'Sunita Maharjan',
    specialty: 'dermatology',
    hospital: 'Blue Pine Clinic',
    feeNpr: 1000,
    experienceYears: 11,
    slotMinutes: 15,
    bio: 'Skin, hair and nail conditions, including acne, eczema and allergies.',
    weeklySchedule: { mon: [afternoon], wed: [afternoon], fri: [morning] },
  },
  {
    id: 'doc-004',
    name: 'Prakash Adhikari',
    specialty: 'pediatrics',
    hospital: 'Riverside Family Clinic',
    feeNpr: 800,
    experienceYears: 14,
    slotMinutes: 15,
    bio: 'Care for babies, children and teenagers: growth, vaccinations and common childhood illnesses.',
    weeklySchedule: weekdays(morning),
  },
  {
    id: 'doc-005',
    name: 'Kabita Tamang',
    specialty: 'gynecology',
    hospital: 'Sunrise Valley Hospital',
    feeNpr: 1200,
    experienceYears: 16,
    slotMinutes: 20,
    bio: "Women's health, pregnancy care and family planning.",
    weeklySchedule: { sun: [afternoon], mon: [afternoon], wed: [morning], thu: [afternoon] },
  },
  {
    id: 'doc-006',
    name: 'Dipesh Gurung',
    specialty: 'orthopedics',
    hospital: 'Himal View Hospital',
    feeNpr: 1200,
    experienceYears: 12,
    slotMinutes: 20,
    bio: 'Bones, joints and sports injuries, including back and knee pain.',
    weeklySchedule: { sun: [evening], tue: [evening], thu: [evening] },
  },
  {
    id: 'doc-007',
    name: 'Mira Shakya',
    specialty: 'ent',
    hospital: 'Blue Pine Clinic',
    feeNpr: 900,
    experienceYears: 9,
    slotMinutes: 15,
    bio: 'Ear, nose and throat problems: sinus trouble, hearing and tonsils.',
    weeklySchedule: { mon: [morning], wed: [morning], fri: [afternoon] },
  },
  {
    id: 'doc-008',
    name: 'Bishal Rana',
    specialty: 'neurology',
    hospital: 'Rhododendron Health Centre',
    feeNpr: 1500,
    experienceYears: 20,
    slotMinutes: 30,
    bio: 'Headaches, migraines, seizures and nerve conditions.',
    weeklySchedule: { sun: [morning], wed: [afternoon] },
  },
  {
    id: 'doc-009',
    name: 'Nisha Pokharel',
    specialty: 'psychiatry',
    hospital: 'Rhododendron Health Centre',
    feeNpr: 1300,
    experienceYears: 10,
    slotMinutes: 30,
    bio: 'Anxiety, depression, sleep problems and stress, in a calm and private setting.',
    weeklySchedule: { mon: [afternoon], tue: [afternoon], thu: [morning] },
  },
  {
    id: 'doc-010',
    name: 'Suresh Karki',
    specialty: 'ophthalmology',
    hospital: 'Lakeside Eye Care',
    feeNpr: 700,
    experienceYears: 13,
    slotMinutes: 15,
    bio: 'Eye checks, vision problems, cataract assessment and eye infections.',
    weeklySchedule: weekdays({ start: '10:00', end: '16:00' }),
  },
  {
    id: 'doc-011',
    name: 'Pooja Thapa Magar',
    specialty: 'dentistry',
    hospital: 'Riverside Family Clinic',
    feeNpr: 600,
    experienceYears: 6,
    slotMinutes: 30,
    bio: 'Check-ups, fillings, cleaning and tooth pain.',
    weeklySchedule: { sun: [morning, evening], tue: [morning], thu: [morning, evening], fri: [morning] },
  },
  {
    id: 'doc-012',
    name: 'Arjun Bhandari',
    specialty: 'gastroenterology',
    hospital: 'Sunrise Valley Hospital',
    feeNpr: 1400,
    experienceYears: 15,
    slotMinutes: 20,
    bio: 'Stomach, liver and digestion problems, including acidity and gastritis.',
    weeklySchedule: { mon: [morning], wed: [morning], fri: [afternoon] },
  },
];
