package com.medhome.nepal

import android.content.Context
import androidx.lifecycle.ViewModelProvider.AndroidViewModelFactory.Companion.APPLICATION_KEY
import androidx.lifecycle.viewmodel.CreationExtras
import com.google.firebase.auth.FirebaseAuth
import com.google.firebase.firestore.FirebaseFirestore
import com.medhome.nepal.data.AdminRepository
import com.medhome.nepal.data.BookingRepository
import com.medhome.nepal.data.FirestoreAdminRepository
import com.medhome.nepal.data.CredentialClient
import com.medhome.nepal.data.CredentialManagerClient
import com.medhome.nepal.data.DataStoreThemeSettings
import com.medhome.nepal.data.DoctorRepository
import com.medhome.nepal.data.FirestoreBookingRepository
import com.medhome.nepal.data.FirestoreDoctorRepository
import com.medhome.nepal.data.FirebaseAuthDataSource
import com.medhome.nepal.data.FirestoreProfileStore
import com.medhome.nepal.data.ListenerRegistry
import com.medhome.nepal.domain.AuthError
import com.medhome.nepal.domain.AuthException
import com.medhome.nepal.domain.BookingError
import com.medhome.nepal.domain.BookingException
import com.medhome.nepal.data.PasswordSaveOffers
import com.medhome.nepal.data.SharedPrefsSavePromptHistory
import com.medhome.nepal.ui.auth.SavedAccountsPrompt
import com.medhome.nepal.session.SessionManager
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.SupervisorJob

/** Manual dependency graph, created once per process by [MedHomeApplication]. */
class AppContainer(context: Context) {
    private val appScope = CoroutineScope(SupervisorJob() + Dispatchers.Main.immediate)

    val credentialClient: CredentialClient = CredentialManagerClient(
        appContext = context.applicationContext,
        // Generated by the google-services plugin from google-services.json.
        webClientId = context.getString(R.string.default_web_client_id),
    )

    /** Every open Firestore listener; sign-out stops them before shutting Firestore down. */
    private val listeners = ListenerRegistry()

    private val authDataSource = FirebaseAuthDataSource(FirebaseAuth.getInstance())

    val sessionManager = SessionManager(
        auth = authDataSource,
        profiles = FirestoreProfileStore { FirebaseFirestore.getInstance() },
        credentials = credentialClient,
        scope = appScope,
        listeners = listeners,
        cancelUpcomingBookings = {
            try {
                bookingRepository.cancelAllUpcoming()
            } catch (e: BookingException) {
                val error = if (e.error == BookingError.NETWORK) AuthError.NETWORK else AuthError.UNKNOWN
                throw AuthException(error, e)
            }
        },
    )

    val passwordSaveOffers = PasswordSaveOffers(SharedPrefsSavePromptHistory(context))

    val savedAccountsPrompt = SavedAccountsPrompt()

    val themeSettings = DataStoreThemeSettings(context)

    val doctorRepository: DoctorRepository = FirestoreDoctorRepository({ FirebaseFirestore.getInstance() }, listeners)

    val bookingRepository: BookingRepository = FirestoreBookingRepository(
        firestore = { FirebaseFirestore.getInstance() },
        currentUid = { authDataSource.currentUser?.uid },
        verifiedClaim = authDataSource::emailVerifiedClaim,
        listeners = listeners,
    )

    /** Only admins' screens use it; the rules refuse everyone else. */
    val adminRepository: AdminRepository = FirestoreAdminRepository(
        firestore = { FirebaseFirestore.getInstance() },
        currentUid = { authDataSource.currentUser?.uid },
        listeners = listeners,
    )
}

val CreationExtras.appContainer: AppContainer
    get() = (checkNotNull(this[APPLICATION_KEY]) as MedHomeApplication).container
