package com.medhome.nepal

import android.content.Context
import androidx.lifecycle.ViewModelProvider.AndroidViewModelFactory.Companion.APPLICATION_KEY
import androidx.lifecycle.viewmodel.CreationExtras
import com.google.firebase.auth.FirebaseAuth
import com.google.firebase.firestore.FirebaseFirestore
import com.medhome.nepal.data.CredentialClient
import com.medhome.nepal.data.CredentialManagerClient
import com.medhome.nepal.data.DataStoreThemeSettings
import com.medhome.nepal.data.FirebaseAuthDataSource
import com.medhome.nepal.data.FirestoreProfileStore
import com.medhome.nepal.data.PasswordSaveOffers
import com.medhome.nepal.data.SharedPrefsSavePromptHistory
import com.medhome.nepal.ui.auth.SavedAccountsPrompt
import com.medhome.nepal.session.SessionManager
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.SupervisorJob

/** Manual dependency graph, created once per process by [MedHomeApplication]. */
class AppContainer(context: Context) {
    private val appScope = CoroutineScope(SupervisorJob() + Dispatchers.Main.immediate)

    val credentialClient: CredentialClient = CredentialManagerClient(
        appContext = context.applicationContext,
        // Generated by the google-services plugin from google-services.json.
        webClientId = context.getString(R.string.default_web_client_id),
    )

    val sessionManager = SessionManager(
        auth = FirebaseAuthDataSource(FirebaseAuth.getInstance()),
        profiles = FirestoreProfileStore { FirebaseFirestore.getInstance() },
        credentials = credentialClient,
        scope = appScope,
    )

    val passwordSaveOffers = PasswordSaveOffers(SharedPrefsSavePromptHistory(context))

    val savedAccountsPrompt = SavedAccountsPrompt()

    val themeSettings = DataStoreThemeSettings(context)
}

val CreationExtras.appContainer: AppContainer
    get() = (checkNotNull(this[APPLICATION_KEY]) as MedHomeApplication).container
