package com.medhome.nepal

import android.content.Context
import androidx.lifecycle.ViewModelProvider.AndroidViewModelFactory.Companion.APPLICATION_KEY
import androidx.lifecycle.viewmodel.CreationExtras
import com.google.firebase.auth.FirebaseAuth
import com.google.firebase.firestore.FirebaseFirestore
import com.medhome.nepal.data.CredentialManagerGoogleClient
import com.medhome.nepal.data.FirebaseAuthDataSource
import com.medhome.nepal.data.FirestoreProfileStore
import com.medhome.nepal.data.GoogleCredentialClient
import com.medhome.nepal.session.SessionManager
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.SupervisorJob

/** Manual dependency graph, created once per process by [MedHomeApplication]. */
class AppContainer(context: Context) {
    private val appScope = CoroutineScope(SupervisorJob() + Dispatchers.Main.immediate)

    val googleClient: GoogleCredentialClient = CredentialManagerGoogleClient(
        appContext = context.applicationContext,
        // Generated by the google-services plugin from google-services.json.
        webClientId = context.getString(R.string.default_web_client_id),
    )

    val sessionManager = SessionManager(
        auth = FirebaseAuthDataSource(FirebaseAuth.getInstance()),
        profiles = FirestoreProfileStore(FirebaseFirestore.getInstance()),
        google = googleClient,
        scope = appScope,
    )
}

val CreationExtras.appContainer: AppContainer
    get() = (checkNotNull(this[APPLICATION_KEY]) as MedHomeApplication).container
